################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &main
      Name: mainMSP
      ID: mainMSP
      MSPDir: crypto-config/peerOrganizations/main.foodchain.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('mainMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('mainMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('mainMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('mainMSP.member')"

      AnchorPeers:
          - Host: peer0.main.foodchain.com
            Port: 7021

          - Host: peer1.main.foodchain.com
            Port: 7022

          - Host: peer2.main.foodchain.com
            Port: 7023

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &MaingroupDefaults
    OrdererType: solo
    Addresses:
        - orderer0.maingroup.main.foodchain.com:7030

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group maingroup #
    MaingroupGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *MaingroupDefaults
            Organizations:
                - *main
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *main

    # Profile used to create channeltx for supplychain #
    Supplychain:
        <<: *ChannelDefaults
        Orderer:
            <<: *MaingroupDefaults
            Organizations:
                - *main
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *main
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *main
