################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_5: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &Orderer
      Name: OrdererMSP
      ID: OrdererMSP
      MSPDir: crypto-config/peerOrganizations/orderer.foodchain.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('OrdererMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('OrdererMSP.member')"

      AnchorPeers:

    - &Farmers
      Name: FarmersMSP
      ID: FarmersMSP
      MSPDir: crypto-config/peerOrganizations/farmer.foodchain.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('FarmersMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('FarmersMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('FarmersMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('FarmersMSP.member')"

      AnchorPeers:
          - Host: peer0.farmer.foodchain.com
            Port: 7041

    - &Distributors
      Name: DistributorsMSP
      ID: DistributorsMSP
      MSPDir: crypto-config/peerOrganizations/distributor.foodchain.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('DistributorsMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('DistributorsMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('DistributorsMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('DistributorsMSP.member')"

      AnchorPeers:
          - Host: peer0.distributor.foodchain.com
            Port: 7061

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "MAJORITY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Group1Defaults
    OrdererType: solo
    Addresses:
        - orderer0.group1.orderer.foodchain.com:7030

    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group group1 #
    Group1Genesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Orderer
                    - *Farmers
                    - *Distributors

    # Profile used to create channeltx for my-channel1 #
    MyChannel1:
        <<: *ChannelDefaults
        Orderer:
            <<: *Group1Defaults
            Organizations:
                - *Orderer
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *Farmers
                    - *Distributors
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *Farmers
                - *Distributors
