name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Application via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 147.182.199.89
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connected to Remote host"
            cd foodchain/Blockchain
            ./fablo prune
            ./fablo generate
            git checkout fablo-target/fabric-docker/scripts/chaincode-functions.sh
            ./fablo up
