# This is a basic workflow that is manually triggered
name: Deploy to digital ocean  # Controls when the action will run.

on:
  push:
    branches:
      - main  # Workflow runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          REMOTE_HOST: 147.182.199.89
          REMOTE_USER: root
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd foodchain/Blockchain 
            git pull
            ./fablo prune
            ./fablo generate
          EOF 
      - name: Wait
        run: sleep 10
      - name: Up the network
        env:
          REMOTE_HOST: 147.182.199.89
          REMOTE_USER: root
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
            cd foodchain/Blockchain
            git checkout fablo-target/fabric-docker/scripts/chaincode-functions.sh
            ./fablo up
          EOF 
        

          
