# This is a basic workflow that is manually triggered
name: Push to Nest  # Controls when the action will run.

on:
  push:
    branches:
      - main  # Workflow runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          REMOTE_HOST: hackclub.app
          REMOTE_USER: karunya
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd ~/app
          git pull origin main
          source .venv/bin/activate
          pip install -r requirements.txt
          kill $(cat ~/app/app.pid)
          nohup gunicorn app:app --bind=127.0.0.1:45600 > nohup.out 2> nohup.err < /dev/null &

          echo cat ~/app/app.pid
          EOF
        
