# This is a basic workflow that is manually triggered
name: Push to Nest  # Controls when the action will run.

on:
  push:
    branches:
      - main  # Workflow runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via SSH
        env:
          REMOTE_HOST: hackclub.app
          REMOTE_USER: karunya
        run: |
          ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST << 'EOF'
          cd /home/karunya/foodchain/Blockchain
          ./fablo down
          git pull
          ./fablo up
          EOF
        
