# This is a basic workflow that is manually triggered
name: Push to Nest  # Controls when the action will run.

on:
  push:
    branches:
      - main  # Workflow runs when code is pushed to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Run Remote SSH Commands
        uses: appleboy/ssh-action@master
        with:
          username: karunya
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your private key in GitHub secrets
          host: hackclub.app
          script: |
            cd foodchain/Blockchain
            git pull 
            ./fablo reset
