name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: 147.182.199.89
          key: ${{secrets.SSH_KEY}}
          username: root

          script: |
            echo "Connected to Remote host"
            cd foodchain/Blockchain
            ./fablo prune
            ./fablo generate
            git checkout fablo-target/fabric-docker/scripts/chaincode-functions.sh
            ./fablo up